### ISSUE TITLE
SyncBatchNorm expected input tensor to be on GPU

### ISSUE THREAD

**Issue by TadaasCirk** [pinery-sls/Pytorch_Yolor_DeepSort#3]
Hi, I get the following error when trying to run track.py
any idea how I can solve it?
```
Traceback (most recent call last):
  File "track.py", line 228, in <module>
    detect(args)
  File "track.py", line 104, in detect
    pred = model(img, augment=opt.augment)[0]
  File "C:\Users\33826\Anaconda3\envs\yolor\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\33826\YOLO\Pytorch_Yolor_DeepSort\./yolor\models\yolo.py", line 177, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "C:\Users\33826\YOLO\Pytorch_Yolor_DeepSort\./yolor\models\yolo.py", line 193, in forward_once
    x = m(x)  # run
  File "C:\Users\33826\Anaconda3\envs\yolor\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\33826\YOLO\Pytorch_Yolor_DeepSort\./yolor\models\common.py", line 181, in forward
    return self.cv4(self.act(self.bn(torch.cat((y1, y2), dim=1))))
  File "C:\Users\33826\Anaconda3\envs\yolor\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\33826\Anaconda3\envs\yolor\lib\site-packages\torch\nn\modules\batchnorm.py", line 682, in forward
    raise ValueError("SyncBatchNorm expected input tensor to be on GPU")
ValueError: SyncBatchNorm expected input tensor to be on GPU
```

**Comment by jgomeher83** [comment]
can you solved?
